# This file is machine-generated - editing it directly is not advised

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Statistics", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "ed2c4abadf84c53d9e58510b5fc48912c2336fbb"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "2.2.0"

[[CpuId]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "f0464e499ab9973b43c20f8216d088b61fda80c6"
uuid = "adafc99b-e345-5852-983c-f28acb93d879"
version = "0.2.2"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "a1b652fb77ae8ca7ea328fa7ba5aa151036e5c10"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.6"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DiffRules]]
deps = ["NaNMath", "Random", "SpecialFunctions"]
git-tree-sha1 = "10dca52cf6d4a62d82528262921daf63b99704a2"
uuid = "b552c78f-8df3-52c6-915a-8e097449b14b"
version = "1.0.0"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[DistributionParameters]]
deps = ["LinearAlgebra", "LoopVectorization", "PaddedMatrices", "ReverseDiffExpressionsBase", "SIMDPirates", "SLEEFPirates", "ScatteredArrays", "SpecialFunctions", "StackPointers", "StructuredMatrices", "VectorizationBase", "VectorizedRNG"]
git-tree-sha1 = "dc56963d81edfae170d87b2f8cd110366b47e603"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/DistributionParameters.jl"
uuid = "c01b26ed-ce4c-5898-8a3a-ab63e1ee7b47"
version = "0.1.0"

[[FunctionWrappers]]
deps = ["Compat"]
git-tree-sha1 = "49bf793ebd37db5adaa7ac1eae96c2c97ec86db5"
uuid = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
version = "1.0.0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[LibGit2]]
deps = ["Printf"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[LoopVectorization]]
deps = ["MacroTools", "SIMDPirates", "SLEEFPirates", "VectorizationBase"]
git-tree-sha1 = "6c2e961b4a5e719fb33f4994d6fdcc763780521e"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/LoopVectorization.jl"
uuid = "bdcacae8-1622-11e9-2a5c-532679323890"
version = "0.1.0"

[[MacroTools]]
deps = ["DataStructures", "Markdown", "Random"]
git-tree-sha1 = "e2fc7a55bb2224e203bbd8b59f72b91323233458"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.3"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[NaNMath]]
git-tree-sha1 = "928b8ca9b2791081dc71a51c55347c27c618760f"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "0.3.3"

[[OpenSpecFun_jll]]
deps = ["Libdl", "Pkg"]
git-tree-sha1 = "65f672edebf3f4e613ddf37db9dcbd7a407e5e90"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.3+1"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "c4c13474d23c60d20a67b217f1d7f22a40edf8f1"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.1.0"

[[PaddedMatrices]]
deps = ["LinearAlgebra", "LoopVectorization", "MacroTools", "Parameters", "Random", "ReverseDiffExpressionsBase", "SIMDPirates", "SLEEFPirates", "SpecialFunctions", "StackPointers", "VectorizationBase", "VectorizedRNG"]
git-tree-sha1 = "836d0d6e614eb44fa5f84d3afe1a2c2276c89376"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/PaddedMatrices.jl"
uuid = "aaaacae8-1622-11e9-2a5c-532679323890"
version = "0.1.0"

[[Parameters]]
deps = ["OrderedCollections"]
git-tree-sha1 = "b62b2558efb1eef1fa44e4be5ff58a515c287e38"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.0"

[[Pkg]]
deps = ["Dates", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "UUIDs"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProbabilityDistributions]]
deps = ["DistributionParameters", "LinearAlgebra", "LoopVectorization", "MacroTools", "PaddedMatrices", "Parameters", "ReverseDiffExpressionsBase", "SIMDPirates", "SLEEFPirates", "ScatteredArrays", "SpecialFunctions", "StackPointers", "StructuredMatrices", "VectorizationBase", "VectorizedRNG"]
git-tree-sha1 = "9c161432f23d5c70aad2e246dfa2de8b1d27d1c2"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/ProbabilityDistributions.jl"
uuid = "3e413219-3d65-5be9-8809-9d8824e993e6"
version = "0.1.0"

[[REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[ReverseDiffExpressionsBase]]
deps = ["LinearAlgebra", "SIMDPirates", "StackPointers", "VectorizationBase"]
git-tree-sha1 = "bd148cbd7b9a394e5d68fb9870af6563a4eb3911"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/ReverseDiffExpressionsBase.jl"
uuid = "6c4e8705-acc8-45e6-99c7-2e34d4f10b96"
version = "0.1.0"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[SIMDPirates]]
deps = ["MacroTools", "VectorizationBase"]
git-tree-sha1 = "3e45c76dfcc349ff208a955e1ce6e92b1be6d15e"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/SIMDPirates.jl"
uuid = "21efa798-c60a-11e8-04d3-e1a92915a26a"
version = "0.1.0"

[[SLEEFPirates]]
deps = ["SIMDPirates", "VectorizationBase"]
git-tree-sha1 = "ba032bbcc7038853867119f4cac383a0051b62a8"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/SLEEFPirates.jl"
uuid = "476501e8-09a2-5ece-8869-fb82de89a1fa"
version = "0.1.0"

[[ScatteredArrays]]
deps = ["LoopVectorization", "PaddedMatrices", "ReverseDiffExpressionsBase", "SIMDPirates", "SLEEFPirates", "StackPointers", "VectorizationBase", "VectorizedRNG"]
git-tree-sha1 = "af0d459c53fce4a626ff7bd81aafe22c019bc2f1"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/ScatteredArrays.jl"
uuid = "7824b66e-fd9c-11e8-16df-0940c56ad1d9"
version = "0.1.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
deps = ["Distributed", "Mmap", "Random", "Serialization"]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[SpecialFunctions]]
deps = ["OpenSpecFun_jll"]
git-tree-sha1 = "268052ee908b2c086cc0011f528694f02f3e2408"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "0.9.0"

[[StackPointers]]
deps = ["MacroTools", "VectorizationBase"]
git-tree-sha1 = "702d959ff214efebbd1ae3b0c7ae6cbb75508764"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/StackPointers.jl"
uuid = "062a3e2c-34b1-4659-9cae-7af421e0d832"
version = "0.1.0"

[[Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[StructuredMatrices]]
deps = ["LinearAlgebra", "LoopVectorization", "PaddedMatrices", "Parameters", "ReverseDiffExpressionsBase", "SIMDPirates", "SLEEFPirates", "StackPointers", "VectorizationBase", "VectorizedRNG"]
git-tree-sha1 = "7f6c801fe6916631ed2bd6043af439810dfdcbc8"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/StructuredMatrices.jl"
uuid = "831e5bd0-d036-11e8-2dea-c77e7dab29a6"
version = "0.1.0"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VectorizationBase]]
deps = ["CpuId", "LinearAlgebra"]
git-tree-sha1 = "1cc48a9bce5c18f2f70fa16cc5b2b39b39332a9e"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/VectorizationBase.jl"
uuid = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"
version = "0.1.0"

[[VectorizedRNG]]
deps = ["Distributed", "Random", "SIMDPirates", "SLEEFPirates", "VectorizationBase"]
git-tree-sha1 = "715523de1ea8c24a745d6a321f1bc201a9cda32e"
repo-rev = "master"
repo-url = "https://github.com/chriselrod/VectorizedRNG.jl"
uuid = "33b4df10-0173-11e9-2a0c-851a7edac40e"
version = "0.1.0"
