name = "ReverseDiffExpressions"
uuid = "b396f49a-4293-4e36-b544-ecf05182fe72"
authors = ["Chris Elrod"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
