name = "ReverseDiffExpressions"
uuid = "b396f49a-4293-4e36-b544-ecf05182fe72"
authors = ["Chris Elrod"]
version = "0.1.0"

[deps]
SIMDPirates = "21efa798-c60a-11e8-04d3-e1a92915a26a"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
